// <auto-generated />
namespace Anketa.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class TestMigration2DefaultUserSeed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestMigration2DefaultUserSeed));
        
        string IMigrationMetadata.Id
        {
            get { return "201509231833243_TestMigration2-Default User Seed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
